version: '3.4'
services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
      target: base
    command: yarn api:dev
    ports:
      - 3333:3333
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - SERVER_URL=${SERVER_URL}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - .:/usr/app/src
      - /usr/app/src/node_modules
    restart: always
  bot:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
      target: base
    command: yarn bot:dev
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
    volumes:
      - .:/usr/app/src
      - /usr/app/src/node_modules
    restart: always
